### PR TITLE
MangaShiro.lua multiple websites fixes and added.

### LINKED ISSUE #659: [website module request] [Olympusscanlation] NEW!!
**Website Information**
* **Name:**  Olympusscanlation
* **Root URL:** https://olympusscanlation.com
* **Directory list URL:** https://olympusscanlation.com/manga/

* **Example manga info URL:** https://olympusscanlation.com/manga/el-principe-perezoso-se-convierte-en-un-genio/
* **Example chapter URL:** https://olympusscanlation.com/el-principe-perezoso-se-convierte-en-un-genio-cap-1/

**Languages**
Spanish

### LINKED ISSUE #666: [bug-website module] mangaboruto.xyz change to
the web link https://mangaboruto.xyz change to https://sensibleiowans.org

### LINKED ISSUE #673: [bug-website module] manhwaland change domain
please fix manhwaland new domain
from
https://manhwaland.cc/ 
to
https://manhwaland.me/
 and new theme are use mangareader

### LINKED ISSUE #682: [website module request] OLYMPUS SCANLATION
Website Information

Name: Olympus Scanlation
Root URL: https://olympusscanlation.com/
Directory list URL: https://olympusscanlation.com/manga/
Example manga info URL: https://olympusscanlation.com/manga/martial-god-asura/
Example chapter URL: https://olympusscanlation.com/martial-god-asura-capitulo-266/
Languages
Spanish

### LINKED ISSUE #690: [website module request] Kumascans
Website Information

Name: KumaScans
Root URL: https://kumascans.com
Directory list URL: https://kumascans.com/manga-lists/
Example manga info URL: https://kumascans.com/manga/1-second/
Example chapter URL: https://kumascans.com/1-second-chapter-1/

Languages
English is all I saw

Additional Information
I noticed they have links in the chapter list to download the full chapter as a zip file. I don't know if that would be something easy for you to point to or not. I am not sure how they link them. 

For example the chapter I listed above uses this link to dl the full thing as a zip file.
https://dl.kumascans.com/?id=262091

### LINKED ISSUE #694: new domain manhwaland
please fix manhwaland new domain
from
https://manhwaland.cc/
to
https://manhwaland.me/
and new theme are use mangareader

### PR DESCRIPTION
**Pull request by Trollam**
resolves #690, resolves #682, resolves #659, resolves #673, resolves #694, resolves #666

### CODE REVIEW

File: lua/modules/MangaShiro.lua [hunk 1]
```diff
@@ -21,7 +21,12 @@ end
 
 function getTitle(x)
 	local title = ''
-	if MODULE.ID == 'b53534f8443e420ea088594c53a3ff39' then title = x.XPathString('//div[@class="thumb"]/img/@alt') end
+
+	local titles = {
+		['b53534f8443e420ea088594c53a3ff39'] = '//div[@class="thumb"]/img/@alt', -- Manhwaland
+		['b5512eeeebbe4aa1a9194f58e8401ca2'] = '//div[@class="thumb"]/img/@alt', -- KumaScans
+	}
+	if titles[MODULE.ID] ~= nil then title = x.XPathString(titles[MODULE.ID]) end
```
Comment (Slasar41) [inline lua/modules/MangaShiro.lua]: Why is this needed?
The title still show up properly even without this.

**Review by Slasar41 — COMMENTED** [review]
There's a ProjectTime commit, you should excluded it.

File: lua/modules/MangaShiro.lua (hunk 1 above)
Comment (Trollam) [reply lua/modules/MangaShiro.lua]: It resolve the issue where some terms other than the title are also displayed, like the language or the format.
For exemple, the title of this [manga](https://kumascans.com/manga/true-education/) is True Education, but it is displayed as True Education English.
I think the solution with gsub to remplace some generic terms is prone to some errors, what happens if one of those terms is legitimately present in the title ? Like if the title really have the term "english" at the end.

Comment (Slasar41) [reply lua/modules/MangaShiro.lua]: I see. In that case maybe do it like this `:gsub('English$', '')`?
That way it'll only remove it if the word is in the last part of title.

Comment (Trollam) [reply lua/modules/MangaShiro.lua]: It may work if a add this rule on a module basis, but at this point the alt of the img also has the title without this trick.

My concern is about all the gsub on line 40 and 41, those are generic and apply on all titles, not only on the one where the website add those terms.
Whap happens if one day a manga have a title with one of those terms? The title will be cut and that will be an issue.

Just for the sake of an exemple, if one of the website in this module host the manga 'I can transform!', the title will be transformed to "I  transform!".
If I add this gsub not based on the module ID and one day a manga with the title "I Teach English" is created and hosted, the title will be shortened.

**Comment by Trollam** [comment]
> There's a ProjectTime commit, you should excluded it.

Yup, done.

File: lua/modules/MangaShiro.lua (hunk 1 above)
Comment (Slasar41) [reply lua/modules/MangaShiro.lua]: Then just add `if title == '' then title = x.XPathString('//div[@class="thumb"]/img/@alt') end` at the top. I think it should be fine. When the website has that string, it should only contains the proper title, right?

Yeah, while you at it you can remove `:gsub('can', '')` safely because the website `Mangacan` doesn't have that word in the title anymore.

**Comment by auraorb13** [comment]
YNTKTS

Pada tanggal Sen, 6 Sep 2021 01.48, Slasar41 ***@***.***>
menulis:

File: lua/modules/MangaShiro.lua (hunk 1 above)
Comment (Trollam) [reply lua/modules/MangaShiro.lua]: I have made these modifications.
